// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Article(props) {
  var visitorCountMsg = "You are visitor number: " + String(props.visitorCount);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: props.title
                    }),
                JsxRuntime.jsx("div", {
                      children: visitorCountMsg
                    }),
                props.children
              ]
            });
}

var make = Article;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
