// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var $$Document = {};

function Counter(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  React.useEffect((function () {
          document.title = "Your clicked " + String(count) + " times!";
        }), [count]);
  var onClick = function (_evt) {
    Curry._1(setCount, (function (prev) {
            return prev + 1 | 0;
          }));
  };
  var msg = "You clicked " + String(count) + " times";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                      children: msg
                    }),
                JsxRuntime.jsx("button", {
                      children: "Click me",
                      onClick: onClick
                    })
              ]
            });
}

var make = Counter;

export {
  $$Document ,
  make ,
}
/* react Not a pure module */
