// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Greetings(props) {
  var name = props.name;
  var greeting = name !== undefined ? "Hello " + name + "!" : "Hello stranger!";
  return JsxRuntime.jsx("div", {
              children: greeting
            });
}

var make = Greetings;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
