// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.mjs";
import * as React from "react";
import * as Router from "./Router.bs.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './index.css'
;

function Main$Header(props) {
  return JsxRuntime.jsx("header", {
              children: JsxRuntime.jsx("nav", {
                    children: JsxRuntime.jsxs("ul", {
                          children: [
                            JsxRuntime.jsx("li", {
                                  children: JsxRuntime.jsx(Router.Link.make, {
                                        route: /* Main */0,
                                        children: "Home"
                                      })
                                }),
                            JsxRuntime.jsx("li", {
                                  children: JsxRuntime.jsx(Router.Link.make, {
                                        route: /* Todo */1,
                                        children: "Todos"
                                      })
                                }),
                            JsxRuntime.jsx("li", {
                                  children: JsxRuntime.jsx(Router.Link.make, {
                                        route: /* Greeting */{
                                          slug: "Jerald"
                                        },
                                        children: "Greeting to Jerald"
                                      })
                                })
                          ],
                          className: "flex items-center gap-x-4"
                        })
                  })
            });
}

var Header = {
  make: Main$Header
};

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsxs(React.StrictMode, {
            children: [
              JsxRuntime.jsx(Main$Header, {}),
              JsxRuntime.jsx(App.make, {})
            ]
          }));
}

export {
  Header ,
}
/*  Not a pure module */
