// Generated by ReScript, PLEASE EDIT WITH CARE


function fromUrl(url) {
  var match = url.path;
  if (!match) {
    return /* Main */0;
  }
  switch (match.hd) {
    case "greetings" :
        var match$1 = match.tl;
        if (match$1 && !match$1.tl) {
          return /* Greeting */{
                  slug: match$1.hd
                };
        } else {
          return ;
        }
    case "todos" :
        if (match.tl) {
          return ;
        } else {
          return /* Todo */1;
        }
    default:
      return ;
  }
}

function toString(route) {
  if (typeof route === "number") {
    if (route !== 0) {
      return "/todos";
    } else {
      return "/";
    }
  } else {
    return "/greetings/" + route.slug + "";
  }
}

export {
  fromUrl ,
  toString ,
}
/* No side effect */
