// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Route from "./Route.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.mjs";

function push(route) {
  RescriptReactRouter.push(Route.toString(route));
}

function Router$Link(props) {
  var $$location = Route.toString(props.route);
  return JsxRuntime.jsx("a", {
              children: props.children,
              href: $$location,
              onClick: (function (evt) {
                  evt.preventDefault();
                  RescriptReactRouter.push($$location);
                })
            });
}

var Link = {
  make: Router$Link
};

export {
  push ,
  Link ,
}
/* react/jsx-runtime Not a pure module */
