// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* AddTodo */0 :
        var todos = state.todos.concat([{
                id: state.nextId,
                content: action._0,
                completed: false
              }]);
        return {
                todos: todos,
                nextId: state.nextId + 1 | 0
              };
    case /* RemoveTodo */1 :
        var id = action._0;
        var todos$1 = state.todos.filter(function (todo) {
              return todo.id !== id;
            });
        return {
                todos: todos$1,
                nextId: state.nextId
              };
    case /* ToggleTodo */2 :
        var id$1 = action._0;
        var todos$2 = Belt_Array.map(state.todos, (function (todo) {
                if (todo.id === id$1) {
                  return {
                          id: todo.id,
                          content: todo.content,
                          completed: !todo.completed
                        };
                } else {
                  return todo;
                }
              }));
        return {
                todos: todos$2,
                nextId: state.nextId
              };
    
  }
}

var initialTodos = [{
    id: 1,
    content: "Try Rescript & React",
    completed: false
  }];

function TodoApp(props) {
  var match = React.useReducer(reducer, {
        todos: initialTodos,
        nextId: 2
      });
  var dispatch = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setContent = match$1[1];
  var content = match$1[0];
  var todos = Belt_Array.map(match[0].todos, (function (todo) {
          return JsxRuntime.jsxs("li", {
                      children: [
                        todo.content,
                        JsxRuntime.jsx("button", {
                              children: "Remove",
                              onClick: (function (param) {
                                  Curry._1(dispatch, {
                                        TAG: /* RemoveTodo */1,
                                        _0: todo.id
                                      });
                                })
                            }),
                        JsxRuntime.jsx("input", {
                              checked: todo.completed,
                              type: "checkbox",
                              onChange: (function (param) {
                                  Curry._1(dispatch, {
                                        TAG: /* ToggleTodo */2,
                                        _0: todo.id
                                      });
                                })
                            })
                      ],
                      className: "grid"
                    }, String(todo.id));
        }));
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    Curry._1(setContent, (function (_prev) {
            return value;
          }));
  };
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Todo List:"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("input", {
                              type: "input",
                              value: content,
                              onChange: onChange
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Add todo",
                              type: "submit",
                              onClick: (function (param) {
                                  Curry._1(dispatch, {
                                        TAG: /* AddTodo */0,
                                        _0: content
                                      });
                                  Curry._1(setContent, (function (param) {
                                          return "";
                                        }));
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsx("ul", {
                      children: todos
                    })
              ],
              className: "mt-4"
            });
}

var make = TodoApp;

export {
  reducer ,
  initialTodos ,
  make ,
}
/* react Not a pure module */
